questions_dir: /home/zhangdw/ReasoningSelfEvolve/questions
questions_file: aime2024_questions.txt
# problem_id: 2030-I-1 # 2024-I-8
problem_id: 2024-II-5
# model: /home/zhangdw/models/DeepSeek/DeepSeek-R1-0528-Qwen3-8B
model: /home/zhangdw/models/Qwen/Qwen3-8B
api_base: http://0.0.0.0:8000
rounds: 80
max_new_tokens: 20000
max_context_length: 32768
temperature: 0.1
top_p: 1.0
verification_max_new_tokens: 25000
max_report_tokens: 5000
output: /home/zhangdw/ReasoningSelfEvolve/outputs/latest_run.log
dry_run: false

